spring.datasource.url = jdbc:mysql://localhost:3306/db_projeto?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = update
server.port = 9091
spring.data.mongodb.database=logs-db
spring.data.mongodb.uri=mongodb+srv://gustavostinghen:<u3QitJBLUKA6I21c>@mongocluester.2wwyr.mongodb.net/logs-db?retryWrites=true&w=majority
